### ISSUE TITLE
Cannot work in macos

### ISSUE THREAD

**Issue by Season0518** [nihui/realsr-ncnn-vulkan#1]
![CEA8EC11-1D59-42C8-8172-C7AE9077FD9B](https://user-images.githubusercontent.com/30144502/82925686-a3d61c00-9fb0-11ea-8582-81a2539d9bc3.jpeg)

**Comment by Season0518** [comment]
Version: Catalina 10.15.3

**Comment by nihui** [comment]
chmod +x realsr-ncnn-vulkan

**Comment by Season0518** [comment]
> chmod +x realsr-ncnn-vulkan

感谢 学到很多

Thanks!
