### ISSUE TITLE
GUI for realsr-ncnn-vulkan

### ISSUE THREAD

**Issue by AaronFeng753** [nihui/realsr-ncnn-vulkan#4]
Hello, I made a GUI for realsr-ncnn-vulkan, probably the first GUI for realsr-ncnn-vulkan, maybe you can add it to README as an unoffical GUI.
Link: https://github.com/AaronFeng753/Waifu2x-Extension-GUI

**Comment by Felixkruemel** [comment]
Video2X was faster I would say ;)
https://github.com/k4yt3x/video2x/actions/runs/115618145

But nonetheless both projects could be linked in my opinion.

**Comment by AaronFeng753** [comment]
> Video2X was faster I would say ;)
> https://github.com/k4yt3x/video2x/actions/runs/115618145
> 
> But nonetheless both projects could be linked in my opinion.

Sorry，I didn't know that project before. I'll delete this issue right away
