### ISSUE TITLE
Buggy outputs with single channel grayscale inputs

### ISSUE THREAD

**Issue by axeldavy** [nihui/realsr-ncnn-vulkan#7]
Hi,

First congrats for the great work. I am quite impressed by your paper and your efforts to make it testable by anyone.

I tried your program on many inputs, and found that single channel grayscale inputs give a buggy output (sometimes black, mix of black and some white, etc).
This is solved by taking the very same image, and concatenate the channel to get a 3 channel image. The result is quite good even though the image is not color.
I tried both png and jpg and both have the bug.

I guess to fix the issue your code should be updated to concatenate the channel 3 times when the input is a single channel grayscale image.

**Comment by nihui** [comment]
fixed in https://github.com/nihui/realsr-ncnn-vulkan/releases/tag/20200818
