### ISSUE TITLE
-i -o in directory mode not re-extension

### ISSUE THREAD

**Issue by wizardlvie** [nihui/realsr-ncnn-vulkan#9]
realsr-ncnn-vulkan.exe -s 4 -t 0 -j 2:2:2 -m models-DF2K_JPEG -x -g 0 -i G:\Users\susu\Desktop\16x9 -o G:\Users\susu\Desktop\16x9\re 

input:
 U1RTKCPC7UY.jpg  
output: 
 U1RTKCPC7UY.jpg.png

**Comment by nihui** [comment]
fixed in https://github.com/nihui/realsr-ncnn-vulkan/releases/tag/20200818
